services:
  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
    - 27017:27017
