services:
  server:
    image: golang:1.21-alpine
    container_name: "lizard"
    environment:
      APP_ENV: "dev"
    volumes:
      - .:/go/src/lizard
    working_dir: /go/src/lizard
    command: /bin/sh -c "go build -o ./main ./cmd/web && ./main"
    ports:
      - 3001:3000
    networks:
      - web_service

  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017

networks:
  web_service: