services:
  server:
    image: golang:1.21-alpine
    container_name: "lizard"
    environment:
      APP_ENV: "dev"
    volumes:
      - .:/go/src/lizard
    working_dir: /go/src/lizard
    command:
      - /bin/sh
      - -c
      - |
        go build -o ./main ./cmd/web
        mv ./main /bin
        /bin/main
    ports:
      - 3001:3000
    networks:
      - web_service
networks:
  web_service: