http:
  baseUrl: "http://localhost:8080"
log:
  name: "lizard"
  env: "dev"
  level: "debug"
mongodb:
  host: "localhost"
  port: 27017
  dbName: "lizard"
cron:
  fetch_trends_and_push_message: "0 0 * * * *"