// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package web

import (
	"github.com/SeanZhenggg/go-utils/logger"
	web2 "lizard/internal/app/web"
	"lizard/internal/config"
	"lizard/internal/controller/web"
	"lizard/internal/controller/web/middleware"
	"lizard/internal/mongo"
	"lizard/internal/repository"
	"lizard/internal/service"
)

// Injectors from wire.go:

func NewAppServer() *appServer {
	iMessageCtrl := web.ProvideMessageCtrl()
	iConfigEnv := config.ProviderIConfigEnv()
	iLogger := logger.ProviderILogger(iConfigEnv)
	iMongoCli := mongo.ProvideMongoDbCli(iConfigEnv)
	iTrendRepository := repository.ProvideTrendRepository()
	iTrendSrv := service.ProviderITrendsSrv(iLogger, iMongoCli, iTrendRepository, iConfigEnv)
	iMessageSrv := service.ProvideLineSrv(iLogger)
	iTrendCtrl := web.ProviderITrendsCtrl(iTrendSrv, iMessageSrv)
	controller := web.ProvideController(iMessageCtrl, iTrendCtrl)
	iResponseMiddleware := middleware.ProvideResponseMiddleware(iLogger)
	iAuthMiddleware := middleware.ProvideAuthMiddleware(iLogger)
	iWebApp := web2.ProvideWebApp(controller, iResponseMiddleware, iAuthMiddleware)
	webAppServer := &appServer{
		iWebApp: iWebApp,
	}
	return webAppServer
}
