on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: master
      - name: transfer code to server via SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.FTP_PORT }}
          localDir: '.'
          remoteDir: ${{ vars.REMOTE_PATH }}
          exclude: vendor/
      - name: run docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
              test -n "$(docker ps -a | awk '/lizard-/ {print $1;}')" && docker stop $(docker ps -a | awk '/lizard-/ {print $1;}') 
              test -n "$(docker ps -a | awk '/lizard-/ {print $1;}')" && docker rm $(docker ps -a | awk '/lizard-/ {print $1;}')
              docker compose up -d