on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: ssh into server, clone project and run docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
              docker stop $(docker ps -a | awk '/lizard-/ {print $1;}') && docker rm $(docker ps -a | awk '/lizard-/ {print $1;}')
              cd /home/seanzheng/sean/side_project
              test -e lizard && rm -rf lizard
              git clone git@github.com:SeanZhenggg/lizard.git
              cd lizard
              docker compose -f docker-compose.yml up -d