on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: master
      - name: transfer code to server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server: ${{ secrets.HOST }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './*'
          remote_path: ${{ vars.REMOTE_PATH }}
          sftp_only: true
      - name: run docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
              test -z "$(docker ps -a | awk '/lizard-/ {print $1;}')" && docker stop $(docker ps -a | awk '/lizard-/ {print $1;}') 
              test -z "$(docker ps -a | awk '/lizard-/ {print $1;}')" && docker rm $(docker ps -a | awk '/lizard-/ {print $1;}')
              docker compose up -d