// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/SeanZhenggg/go-utils/logger"
	"lizard/source/app/web"
	"lizard/source/config"
	"lizard/source/controllers"
	"lizard/source/controllers/middleware"
	"lizard/source/mongo"
	"lizard/source/repository"
	"lizard/source/service"
)

// Injectors from wire.go:

func NewAppServer() *appServer {
	iConfigEnv := config.ProviderIConfigEnv()
	iLogger := logger.ProviderILogger(iConfigEnv)
	iMongoCli := mongo.ProvideMongoDbCli(iConfigEnv)
	iTrendRepository := repository.ProvideTrendRepository()
	iTrendSrv := service.ProviderITrendsSrv(iLogger, iMongoCli, iTrendRepository)
	iTrendCtrl := controllers.ProviderITrendsCtrl(iTrendSrv)
	controller := controllers.ProvideController(iTrendCtrl)
	iResponseMiddleware := middleware.ProvideResponseMiddleware()
	iAuthMiddleware := middleware.ProvideAuthMiddleware(iLogger)
	iWebApp := web.ProvideWebApp(controller, iResponseMiddleware, iAuthMiddleware)
	serverAppServer := &appServer{
		iWebApp: iWebApp,
	}
	return serverAppServer
}
